name: Deploy Migrations to Staging Magdeburg

on:
  push:
    branches:
      - staging-magdeburg
  workflow_dispatch:

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.36.6

      - run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
